### ISSUE TITLE
build map

### ISSUE THREAD

**Issue by cfhaak** [NestroyCA/nestroyca-astro-base#10]
Need to create a map to display coordinates derived from corpus and stored in pmb.
@csae8092 could you please drop a link on what library/services I should use for that?

**Comment by csae8092** [comment]
https://leafletjs.com/ (oldie but gooldie) plus https://github.com/Leaflet/Leaflet.markercluster

siehe e.g. https://schnitzler-briefe.acdh.oeaw.ac.at/listplace.html (hier gibts auch gleich eine verbindung zur tabelle, sprich es werden nur gefilterte ergebisse angezeigt


hot fancy stuff: https://deck.gl/

 (see e.g. https://schnitzler-orte.acdh.oeaw.ac.at/towers.html)

**Comment by cfhaak** [comment]
thanks a lot

**Comment by cfhaak** [comment]
When to best get data from https://github.com/NestroyCA/baserow-entities/raw/main/json_dumps/places.json?
For now, I do it at buildtime, create list of triples and iterate over it, creating the pins

**Comment by cfhaak** [comment]
better like that? https://leafletjs.com/examples/quick-start/

**Comment by csae8092** [comment]
Whatever gets the Job done https://github.com/Leaflet/Leaflet.markercluster/blob/master/example/geojson.html

**Comment by cfhaak** [comment]
after failing to use the provided components I came up with something
