### ISSUE TITLE
page not resolving to the right domain

### ISSUE THREAD

**Issue by cfhaak** [NestroyCA/nestroyca-astro-base#24]
service was moved to nginx from apache proxy
After moving the proxy doesn't work, relative links from index.html resolve to the github pages domain, regardless of the page existing in the correct domain.
from https://nestroyca.acdh-dev.oeaw.ac.at/ href="/terms" resolves to https://nestroyca.github.io/nestroyca-astro-base/terms/ while https://nestroyca.acdh-dev.oeaw.ac.at/terms/ exists.

Bottom line: relative links are not resolved to the right domain, even though the browser shows the correct destination when hover

**Comment by cfhaak** [comment]
maybe its due to the old apache proxy not being restartet, might be interfering with traffic

**Comment by acdh** [comment]
The problem is not related to the proxy. It seems that PUBLIC_APP_BASE_URL env variable has no effect.

**Comment by cfhaak** [comment]
Okay, will check this out

**Comment by cfhaak** [comment]
It seems, that this issue was caused, by missing trailing slashes in the astro links. Nginx no has a rule, to add them via regex, since it is an desirable default, redirect accordingly
